//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMVC.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCF")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectMVC.ProductServiceReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisponivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectMVC.ProductServiceReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Disponivel {
            get {
                return this.DisponivelField;
            }
            set {
                if ((this.DisponivelField.Equals(value) != true)) {
                    this.DisponivelField = value;
                    this.RaisePropertyChanged("Disponivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((this.ProdutoIdField.Equals(value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCF")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProjectMVC.ProductServiceReference.Produto[] ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectMVC.ProductServiceReference.Produto[] Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindAll", ReplyAction="http://tempuri.org/IProductService/FindAllResponse")]
        ProjectMVC.ProductServiceReference.Produto[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindAll", ReplyAction="http://tempuri.org/IProductService/FindAllResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Find", ReplyAction="http://tempuri.org/IProductService/FindResponse")]
        ProjectMVC.ProductServiceReference.Produto Find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Find", ReplyAction="http://tempuri.org/IProductService/FindResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> FindAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/New", ReplyAction="http://tempuri.org/IProductService/NewResponse")]
        ProjectMVC.ProductServiceReference.Produto New(ProjectMVC.ProductServiceReference.Produto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/New", ReplyAction="http://tempuri.org/IProductService/NewResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> NewAsync(ProjectMVC.ProductServiceReference.Produto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Update", ReplyAction="http://tempuri.org/IProductService/UpdateResponse")]
        ProjectMVC.ProductServiceReference.Produto Update(ProjectMVC.ProductServiceReference.Produto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Update", ReplyAction="http://tempuri.org/IProductService/UpdateResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> UpdateAsync(ProjectMVC.ProductServiceReference.Produto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteId", ReplyAction="http://tempuri.org/IProductService/DeleteIdResponse")]
        ProjectMVC.ProductServiceReference.Produto DeleteId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/DeleteId", ReplyAction="http://tempuri.org/IProductService/DeleteIdResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> DeleteIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Delete", ReplyAction="http://tempuri.org/IProductService/DeleteResponse")]
        ProjectMVC.ProductServiceReference.Produto Delete(ProjectMVC.ProductServiceReference.Produto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/Delete", ReplyAction="http://tempuri.org/IProductService/DeleteResponse")]
        System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> DeleteAsync(ProjectMVC.ProductServiceReference.Produto pro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : ProjectMVC.ProductServiceReference.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<ProjectMVC.ProductServiceReference.IProductService>, ProjectMVC.ProductServiceReference.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectMVC.ProductServiceReference.Produto[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public ProjectMVC.ProductServiceReference.Produto Find(int id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> FindAsync(int id) {
            return base.Channel.FindAsync(id);
        }
        
        public ProjectMVC.ProductServiceReference.Produto New(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.New(pro);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> NewAsync(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.NewAsync(pro);
        }
        
        public ProjectMVC.ProductServiceReference.Produto Update(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.Update(pro);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> UpdateAsync(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.UpdateAsync(pro);
        }
        
        public ProjectMVC.ProductServiceReference.Produto DeleteId(int id) {
            return base.Channel.DeleteId(id);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> DeleteIdAsync(int id) {
            return base.Channel.DeleteIdAsync(id);
        }
        
        public ProjectMVC.ProductServiceReference.Produto Delete(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.Delete(pro);
        }
        
        public System.Threading.Tasks.Task<ProjectMVC.ProductServiceReference.Produto> DeleteAsync(ProjectMVC.ProductServiceReference.Produto pro) {
            return base.Channel.DeleteAsync(pro);
        }
    }
}
